### ISSUE TITLE
Failing to extract excerpt if first paragraph only contains an image

### ISSUE THREAD

**Issue by pixelastic** [martinheidegger/excerpt-html#7]
Hello,

I have markdown content (blog posts) where the first paragraph(s) usually only contains an image and the actual textual content starts after. This module fails to correctly extract the excerpt in that case, returning an empty string instead.

```javascript
test('ignore empty first paragraphs', function (t) {
  t.equals(excerptHtml('<p><img src="cat.png" /></p><p><img src="dog.png" /></p><p>test</p>', { 
  }), 'test')
  t.end()
})
```

Would you be interested in a PR fixing this behavior?

**Comment by martinheidegger** [comment]
Oh, good catch! Yes, it would help I think to have a good logic here and I am happy to merge a PR for this!

**Comment by pixelastic** [comment]
Submitted a PR for that here, https://github.com/martinheidegger/excerpt-html/pull/8 let me know what you think
