### ISSUE TITLE
null is not an object (evaluating 'html.search')

### ISSUE THREAD

**Issue by joseito-terence** [martinheidegger/excerpt-html#9]
I'm getting the following error in react-native/expo, was previously working fine.
![image](https://user-images.githubusercontent.com/74445627/197690360-2e3c7623-e9b5-4bb0-8583-e77f9ac621ab.png)

**Comment by martinheidegger** [comment]
Hello @joseito-terence,

It looks to me like you have changes in esm/cjs compilation. Probably a bundler setting in your project has changed?! That treats cheerio with esm compatibility (ironically probably intended to prevent this sort of problems)

**Comment by joseito-terence** [comment]
I just fixed it by replacing this library with another.
Use `string-strip-html@8.3.0`

**Comment by martinheidegger** [comment]
🎉
